export const categories: any = [
  '4K',
  '2022',
  'Lançamentos',
  'Comédia',
  'Ação',
  'Ficção',
  'Shows Internacionais',
  'Terror',
  'Documentários',
  'Animação/Infantil',
  'Nacional',
  'Romance',
  'Drama/Suspense',
  'Policial',
  'Clássicos',
  'Adultos',
];
